name: dog-breed-classifier
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - nbgitpuller
  - ipywidgets==7.8.1
  - matplotlib==3.10.0
  - numpy==2.2.2
  - pandas==2.2.3
  - Pillow==11.1.0
  - scikit_learn==1.6.1
  - pip
  - pip:
    - nbgitpuller
    - ipywidgets==7.8.1
    - matplotlib==3.10.0
    - numpy==2.2.2
    - pandas==2.2.3
    - Pillow==11.1.0
    - scikit_learn==1.6.1
